version: "3.5"
services:
  pop-solr:
    image: solr:9.2.1
    command:
      - "-c"
      - "-a"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:58983"
    restart: always
    healthcheck:
      test: lsof -n -i :6627
      interval: 30s
      timeout: 3s
      retries: 3
